version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
  - dependency-name: jinja2
    versions:
    - 2.11.3
  - dependency-name: bleach
    versions:
    - 3.3.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: pyproj
    versions:
    - 3.0.0.post1
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
    - 12.7.1
    - 12.7.4
    - 12.8.1
    - 12.8.2
    - 13.0.0
    - 13.0.10
    - 13.0.11
    - 13.0.12
    - 13.0.13
    - 13.0.14
    - 13.0.15
    - 13.0.16
    - 13.0.4
    - 13.0.5
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.6
    - 13.1.7
  - dependency-name: "@sentry/tracing"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.2
    - 6.3.3
  - dependency-name: "@sentry/react"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.2
    - 6.3.3
  - dependency-name: "@formatjs/intl-pluralrules"
    versions:
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.15
    - 4.0.16
    - 4.0.6
    - 4.0.7
    - 4.0.8
    - 4.0.9
  - dependency-name: react-intl
    versions:
    - 5.10.19
    - 5.11.0
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.4
    - 5.12.5
    - 5.13.0
    - 5.13.2
    - 5.13.3
    - 5.13.4
    - 5.13.5
    - 5.14.0
    - 5.14.1
    - 5.15.0
    - 5.15.1
    - 5.15.3
    - 5.15.4
    - 5.15.5
    - 5.15.7
    - 5.15.8
    - 5.16.0
    - 5.17.0
    - 5.17.1
  - dependency-name: "@formatjs/intl-locale"
    versions:
    - 2.4.14
    - 2.4.15
    - 2.4.16
    - 2.4.17
    - 2.4.19
    - 2.4.20
    - 2.4.21
    - 2.4.22
    - 2.4.23

  - dependency-name: react-datepicker
    versions:
    - 3.7.0
  - dependency-name: reactjs-popup
    versions:
    - 2.0.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@formatjs/intl-relativetimeformat"
    versions:
    - 8.0.4
    - 8.0.5
    - 8.0.6
    - 8.1.0
    - 8.1.2
    - 8.1.3
    - 8.1.4
    - 8.1.5
    - 8.1.6
  - dependency-name: react-tooltip
    versions:
    - 4.2.14
    - 4.2.15
    - 4.2.16
    - 4.2.17
    - 4.2.18
  - dependency-name: react-redux
    versions:
    - 7.2.3
    - 7.2.4
  - dependency-name: redux
    versions:
    - 4.1.0
  - dependency-name: react-datepicker
    versions:
    - 3.6.0
    - 3.8.0
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.6
  - dependency-name: date-fns
    versions:
    - 2.20.0
    - 2.20.1
    - 2.21.0
    - 2.21.1
  - dependency-name: workbox-expiration
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.5
  - dependency-name: marked
    versions:
    - 2.0.2
    - 2.0.3
  - dependency-name: msw
    versions:
    - 0.27.0
    - 0.27.2
    - 0.28.0
    - 0.28.1
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.1.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
    - 11.2.6
  - dependency-name: react-dropzone
    versions:
    - 11.3.0
    - 11.3.1
    - 11.3.2
  - dependency-name: use-query-params
    versions:
    - 1.2.1
    - 1.2.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: query-string
    versions:
    - 6.14.1
    - 7.0.0
  - dependency-name: react-final-form
    versions:
    - 6.5.3
  - dependency-name: workbox-routing
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-core
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-recipes
    versions:
    - 6.1.2
  - dependency-name: workbox-strategies
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-precaching
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@hotosm/iso-countries-languages"
    versions:
    - 1.1.0
  - dependency-name: slug
    versions:
    - 4.0.3
  - dependency-name: "@mapbox/mapbox-gl-draw"
    versions:
    - 1.2.1
    - 1.2.2
  - dependency-name: react-scripts
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: react-select
    versions:
    - 4.1.0
  - dependency-name: react-placeholder
    versions:
    - 4.1.0
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
  - dependency-name: alembic
    versions:
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: sentry-sdk[flask]
    versions:
    - 0.20.3
  - dependency-name: greenlet
    versions:
    - 1.0.0
  - dependency-name: gevent
    versions:
    - 21.1.2
  - dependency-name: oauthlib
    versions:
    - 3.1.0
  - dependency-name: bleach
    versions:
    - 3.3.0
  - dependency-name: flask-oauthlib
    versions:
    - 0.9.6
  - dependency-name: flask-cors
    versions:
    - 3.0.10
  - dependency-name: attrs
    versions:
    - 20.3.0
  - dependency-name: werkzeug
    versions:
    - 1.0.1
  - dependency-name: black
    versions:
    - 20.8b1
  - dependency-name: geojson
    versions:
    - 2.5.0
