language: python
python:
    - "3.6"

dist: trusty

cache:
  pip: true
  apt: true
  directories:
    - node_modules
    - $HOME/.cache/pip
    - $HOME/build/hotosm/tasking-manager/env

sudo: true

env:
  global:
    - DEPLOY_BRANCH=master
    - STAGING_BRANCH=develop

before_install:
  - chmod +x ./devops/ci/shippable_deploy.sh
  - chmod +x ./devops/ci/travisci_1_dependencies.sh
  - chmod +x ./devops/ci/travisci_2_tests.sh
  - pip install virtualenv
  - deactivate #TravisCI venv

install:
  - ./devops/ci/travisci_1_dependencies.sh

script:
  - ./devops/ci/travisci_2_tests.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: "./devops/ci/shippable_deploy.sh"
    on:
      branch: "${DEPLOY_BRANCH}"
