language: python
python:
    - "3.6"

cache: pip

# This before_install list is only used for the test stage.
before_install:
  - echo 'before install'

script:
  - echo 'script'

jobs:
  include:
    - stage: install dependencies
      script:
    # Install latest LTS node
      - env
      - pwd
      - echo $TRAVIS_BUILD_DIR
      - apt-get update
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - apt-get install nodejs
      - node --version
    # Install NPM packages and build client from gulpfile
      - cd client
      - npm install
      - ./node_modules/.bin/gulp build
      - cd ..
    # Install Python dependencies
      - python --version
      - apt-get install -y libgeos-c1 libgeos-dev  # Required for shapely
      - pip install -r requirements.txt
    - stage: run tests
      script:
    # JS Unit Tests
      - cd tests/client
      - ../../client/node_modules/.bin/karma start ./karma.conf.js --single-run --browsers PhantomJS --reporters junit
      - cd ../..
    # Run Python tests
      - cd $TRAVIS_BUILD_DIR
      - nosetests ./tests/server --with-xunit --xunit-file ./shippable/testresults/unitresults.xml --with-coverage --cover-erase --cover-package=./server
      - coverage xml -o shippable/codecoverage/coverage.xml
    - stage: Run deploy script to manage deploy to appropriate environment
      script:
      - . ./devops/ci/shippable_deploy.sh
