language: python
python:
    - "3.6"

cache:
  pip: true
  apt: true
  directories:
    - node_modules

sudo: true

env:
  global:
    - DEPLOY_BRANCH=master
    - STAGING_BRANCH=develop

# This before_install list is only used for the test stage.
before_install:
  - chmod +x ./devops/ci/shippable_deploy.sh

script:
    # Install latest LTS node
      - env
      - pwd
      - echo $TRAVIS_BUILD_DIR
      - sudo apt-get update
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install nodejs
      - node --version
    # Install NPM packages and build client from gulpfile
      - cd client
      - sudo npm install
      - ./node_modules/.bin/gulp build
      - cd ..
    # Required to display test results in Shippable GUI
      - mkdir -p shippable/testresults
      - mkdir -p shippable/codecoverage
    # JS Unit Tests
      - cd tests/client
      - ../../client/node_modules/.bin/karma start ./karma.conf.js --single-run --browsers PhantomJS --reporters junit
      - cd ../..
    # Install Python dependencies
      - python --version
      - apt-get install -y libgeos-c1 libgeos-dev  # Required for shapely
      - pip install -r requirements.txt
    # Run Python tests
      - nosetests ./tests/server --with-xunit --xunit-file ./shippable/testresults/unitresults.xml --with-coverage --cover-erase --cover-package=./server
      - coverage xml -o shippable/codecoverage/coverage.xml

deploy:
  - provider: script
    skip_cleanup: true
    script: "./devops/ci/shippable_deploy.sh"
    on:
      branch: "${DEPLOY_BRANCH}"
