language: python
python:
    - "3.6"

cache:
  pip: true
  apt: true
  directories:
    - node_modules

sudo: true

env:
  global:
    - DEPLOY_BRANCH=master
    - STAGING_BRANCH=develop

before_install:
  - chmod +x ./devops/ci/shippable_deploy.sh
  - chmod +x ./devops/ci/travisci_1_dependencies.sh
  - chmod +x ./devops/ci/travisci_2_tests.sh

script:
  - ./devops/ci/travisci_1_dependencies.sh
  - ./devops/ci/travisci_2_tests.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: "./devops/ci/shippable_deploy.sh"
    on:
      branch: "${DEPLOY_BRANCH}"
