# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines starting with the hashtag symbol are comments
# AppSpec File Reference  https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
#
# DO NOT CHANGE
version: 0.0
#
os: linux 
#
# During the Install deployment lifecycle event (which occurs between the 
#   BeforeInstall and AfterInstall events), copy the specified files 
#   in "source" starting from the root of the revision's file bundle 
#   to "destination" on the Amazon EC2 instance.
# Specify multiple "source" and "destination" pairs if you want to copy 
#   from multiple sources or to multiple destinations.
# If you are not copying any files to the Amazon EC2 instance, then remove the
#   "files" section altogether. A blank or incomplete "files" section
#   may cause associated deployments to fail.
files:
  - source: /
    destination: /tasking-manager
  - source: /tasking-manager.service
    destination: /etc/systemd/system
#
permissions:
  - object: /tasking-manager
    pattern: "*"
    owner: root
    group: root
    mode: 644
    type:
      - directory
#
hooks:
  ApplicationStop:
    - location: /scripts/aws/cloudformation/service-stop.sh
      timeout: 200
      runas: root
  ApplicationStart:
    - location: /scripts/aws/cloudformation/service-start.sh
      timeout: 200
      runas: root
