version: '2'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TM_DB=postgresql://hottm:hottm@postgresql/tasking-manager
    command: "false"
  app:
    extends:
      service: base
    depends_on:
      - postgresql
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - postgresql
    command: python manage.py runserver
  migration:
    extends:
      service: base
    depends_on:
      - postgresql
    links:
      - postgresql
    command: python manage.py db upgrade
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=hottm
      - POSTGRES_PASSWORD=hottm
      - POSTGRES_DB=tasking-manager
    expose:
      - "5432"
    logging:
      driver: none
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  stage:
  downloads:
