# To use this file, run `docker-compose up`.
version: '3'

services:

  # Main application
  app:
    build: .
    environment:
      - TM_DB=postgresql://hottm:hottm@postgresql/tasking-manager
    depends_on:
      - postgresql
    ports:
      - "5000:5000"
    links:
      - postgresql
    command: python manage.py runserver -h 0.0.0.0

  # Migration service
  migration:
    build: .
    depends_on:
      - postgresql
    links:
      - postgresql
    command: python manage.py db upgrade

  # Database
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=hottm
      - POSTGRES_PASSWORD=hottm
      - POSTGRES_DB=tasking-manager
    expose:
      - "5432"
    logging:
      driver: none
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  stage:
  downloads:
