# To use this file, run `docker-compose up`.
version: "3.4"

x-template-config: &template
  build:
    context: "."
    dockerfile: "./scripts/docker/Dockerfile.backend"
  image: hotosm-tasking-manager:base
  env_file: ${ENV_FILE:-tasking-manager.env}
  volumes:
    - .:/usr/src/app
  depends_on:
    - postgresql
  networks:
    - tm-web

services:
  # Main application
  backend:
    <<: *template
    container_name: tm_backend
    restart: unless-stopped
    ports:
      - 5000:5000

  migration:
    <<: *template
    container_name: tm_migration
    restart: on-failure
    command: python manage.py db upgrade
    depends_on:
      - backend

  frontend:
    container_name: tm_frontend
    build:
      context: "."
      dockerfile: "./scripts/docker/Dockerfile.frontend"
    image: hotosm-tasking-manager:frontend
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 3000:80
    networks:
      - tm-web

  postgresql:
    image: mdillon/postgis:11
    container_name: postgresql
    restart: always
    env_file: ${ENV_FILE:-tasking-manager.env}
    networks:
      - tm-web

networks:
  tm-web:
    external: true
