# To use this file, run `docker-compose up`.
version: '3.4'

x-backend-config: &backend
  build:
    context: "."
    dockerfile: "./scripts/docker/Dockerfile.backend"

services:
  # Main application
  backend:
    <<: *backend
    volumes:
      - .:/usr/src/app

  # Migration service
  migration:
    <<: *backend
    volumes:
      - .:/usr/src/app

  postgresql:
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"

  frontend:
    build:
      context: "."
      dockerfile: "./scripts/docker/Dockerfile.frontend"
    volumes:
      - ".:/usr/src/app"
    labels:
      - TM_APP_API_URL=https://tasks.smartcitiestransport.com/api
      - traefik.http.routers.frontend.rule=Host(`localhost`, `tasks.smartcitiestransport.com`) || Host(`localhost`)
      # - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`127.0.0.1`)
      - traefik.http.services.frontend.loadbalancer.server.port=80

volumes:
  postgresql-data: