# To use this file, run `docker-compose up`.
version: '2'

services:

  # Define base for application
  base:
    build: .
    env_file: .env
    command: "false"

  # Main application
  app:
    extends:
      service: base
    depends_on:
      - postgresql
    ports:
      - "5000:5000"
    links:
      - postgresql
    command: python manage.py runserver -h 0.0.0.0

  # Migration service
  migration:
    extends:
      service: base
    depends_on:
      - postgresql
    links:
      - postgresql
    command: python manage.py db upgrade

  # Database
  postgresql:
    image: mdillon/postgis:9.6
    env_file: .env
    expose:
      - "5432"
    logging:
      driver: none
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  stage:
  downloads:
