services:
  traefik:
    image: traefik:v2.3
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
    networks:
      - tm-web

  frontend:
    labels:
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      - traefik.http.services.frontend.loadbalancer.server.port=80

  backend:
    labels:
      - traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api/`)
      - traefik.http.services.backend.loadbalancer.server.port=5000

