site_name: tasking-manager
site_description: The HOT Tasking Manager
# strict: true
site_url: "https://www.hotosm.org"

repo_name: "hotosm/tasking-manager"
repo_url: "https://github.com/hotosm/tasking-manager/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  favicon: images/favicon.png
  logo: images/hot_logo.png
  # custom_dir: docs/overrides

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
#  - mkdocs_protobuf:
#      proto_dir: */*.proto *.proto
  - search
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - About: about.md
  - For Developers:
#       - Understanding the Code: developers/understanding-the-code.md
      - Contributing Guidelines: developers/contributing-guidelines.md
      - Development Setup: developers/development-setup.md
      - Versions and Releases: developers/versions-and-releases.md
  - For Sysadmins:
#      - Monitoring and Logging: sysadmins/monitoring-logging.md
#      - Networking: sysadmins/networking-connectivity.md
      - Deployment: sysadmins/deployment.md
      - CI: sysadmins/ci-cd.md
      - Architecture: sysadmins/architecture.md
#      - Security and Reliability: sysadmins/security-reliability-processes.md
  - Class Hierarchy: apidocs/html/index.html
  - License: LICENSE.md
#  - Changelog: CHANGELOG.md
